version: '3.1'
services:
  mongo:
    image: mongo:7.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  dbms:
    image: swcdbms:v1
    restart: always
    depends_on: 
      - mongo
    ports:
      - 8088:8088
